[project]
name = "ml-basics"
version = "0.1.0"
description = "Notebooks of ML Basics"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "scipy>=1.15.1",
    "torch>=2.6.0",
    "gpytorch",
]
